### ISSUE TITLE
Release or branch for v1.4.1 without the deprecation warnings

### ISSUE THREAD

**Issue by zoka123** [sonata-project/twig-extensions#185]
## Feature Request

Using this package on `v1.4.1` results in known deprecation warnings for `sonata.twig.deprecated_template_extension`.

These are resolved with https://github.com/sonata-project/twig-extensions/commit/85e2f53679ba05246e1c28a308b0aaedba2cbaa4 and released under the `v1.4.2` but the [`v1.4.2` release also introduces required upgrades](https://github.com/sonata-project/twig-extensions/compare/1.4.1...1.4.2#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R25) for the `sonata-project/doctrine-extensions` package on a [version](https://github.com/sonata-project/sonata-doctrine-extensions/blob/1.10.0/composer.json#L29) that defines conflicts with `"doctrine/doctrine-bundle": "<2.0",`

This leaves some of us in a deadlock as we can't get rid of these deprecation warnings on `v1.4.1` even though the fix is available, since the next patch release (i.e. `v1.4.2`) introduces requirements for updating other packages.

I've tried locking this package to a specific commit hash (E.g. `1.x-dev#85e2f53679ba05246e1c28a308b0aaedba2cbaa4`) as Composer checks for the most recent `composer.json` on the `1.x` branch and raises conflicts introduced after this commit. ([See here](https://getcomposer.org/doc/04-schema.md#package-links))

The solution for my use case could be to fork this repository and target it on the desired branch, but it seems like it would be a good idea to provide a common solution in this repository for others as well, and prevent unnecessary forks.

The solution could be as simple as keeping a branch e.g. `1.4.1-deprecation-fix` (suggestions for the branch name are welcome) at the [commit introducing the fix]( https://github.com/sonata-project/twig-extensions/commit/85e2f53679ba05246e1c28a308b0aaedba2cbaa4) so we can pin the dependency to that specific branch with Composer `"sonata-project/twig-extensions": "1.4.1-deprecation-fix-dev@dev"`

---

I will be happy to do the work if the suggested solution seems correct. I'm also open for pointers in another direction that could lead to a version without deprecation warnings that don't require other dependencies to upgrade.

Thanks in advance!

**Comment by VincentLanglet** [comment]
Hi.

I'm sorry but I don't think we will keep multiple branch this way ; especially for a deprecation which is not a blocking point.
If you want to get read of the deprecation, I recommend you to upgrade `doctrine/doctrine-bundle` instead.
But you can still fork it, create your on branch `1.4.1-deprecation-fix-dev` and use it on composer indeed.

**Comment by zoka123** [comment]
Thanks Vincent, 

No problem, it makes sense. We will alias this package to use forked branch.

Thanks for the quick reply! Cheers

**Comment by martin-georgiev** [comment]
@VincentLanglet please allow me to disagree with the versioning approach that was taken.

My understanding (probably shared by a sizeable portion of Sonata's users) is that the project follows [semantic versioning](https://semver.org/) for its releases. This is indeed the versioning approach most commonly adopted by the PHP open-source society. I looked in more details in the changes between releases [1.4.1 and 1.4.2](https://github.com/sonata-project/twig-extensions/compare/1.4.1...1.4.2). There are [certain changes to `composer.json`](https://github.com/sonata-project/twig-extensions/compare/1.4.1...1.4.2#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) that can be considered out of line with semantic versioning.
Namely, the main principle used for classifying a release as `PATCH` (a version that should be made for backwards-compatible bug fixes) was broken by bumping the minimum requirements for the PHP version and `sonata-project/doctrine-extensions`.

<img width="1083" alt="Screenshot 2021-01-19 at 22 00 35" src="https://user-images.githubusercontent.com/4849482/105098977-8f044680-5ab3-11eb-8857-392a1ef61d29.png">


It is not ideal (and definitely not predictable) that those requirement changes were not rectified in the changelog and that the newly introduced code does not make use of them. It is not always possible in a project to accommodate for an unexpected major bump in otherwise critical requirement like `doctrine/doctrine-bundle`, especially as [version series 1 of DoctrineBundle](https://github.com/doctrine/DoctrineBundle/releases/tag/1.12.13) is still actively maintained.

Please, correct me if I am wrong and misunderstood something.

**Comment by VincentLanglet** [comment]
Bumping dependencies are not related to semantic versioning since composer are resolving the right version.
This bump was made here https://github.com/sonata-project/twig-extensions/pull/148 because the CI was failing.

You're taking the wrong fight. There is nothing wrong with what was done here in the twig extension.
What you want is that the doctrine-extensions still support Doctrine 1. As soon as it will be done, you'll be able to use the last twig-extensions version.

You're free to open a PR to try to provide a wider range of support in the next release of sonata-doctrine-extensions.
